[package]
name = "testgame"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_rapier3d = "0.11.0"
log = "0.4.14"
nalgebra = "0.29.0"
simple_logger = "1.13.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
